language: node_js
node_js:
  - "node"
install:
  - npm ci
jobs:
    include:
      - stage: "Test"
        branches:
          only:
            - master
        script:
          - "npm test"
      - stage: "Deploy"
        script: skip
        deploy:
          - name: "Deploy to Github Pages"
            provider: pages
            github_token: $GITHUB_TOKEN
            skip_cleanup: true
            keep_history: true
            script: bash bin/update-gh-page "$TRAVIS_TAG" true
            on:
              condition: "$TRAVIS_TAG =~ v.+@origin"
          - name: "Release to NPM"
            provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_TOKEN
            skip_cleanup: true
            on:
              condition: "$TRAVIS_TAG =~ v.+@origin"
notifications:
  email: false