language: node_js
node_js:
  - "node"
install:
  - npm ci
stages:
  - name: test
    if: branch = master
  - name: deploy-gh
    if: tag =~ ^v.+@origin$
  - name: release-npm
    if: tag =~ ^v.+@origin$
jobs:
    include:
      - stage: test
        script: "npm test"
      - stage: deploy-gh
        name: "Deploy to Github"
        deploy:
          provider: pages
          github_token: $GITHUB_TOKEN
          skip_cleanup: true
          keep_history: true
          script: bash bin/update-gh-page "$TRAVIS_TAG" true
      - stage: release-npm
        name: "Release to NPM"
        deploy:
          provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
notifications:
  email: false